#
# Copyright Jean-Charles Lambert, 2020
#
# - YAML file for Continous Integration / Continous Deployement
# - glnemo2 packages (RPM or DEB) are automatically
#   generated at new commit for different linux distribution
#
# - Documentation :
#   https://docs.gitlab.com/ee/ci/yaml/

stages:
- build

variables :
  BUILD       : 0
  ONEBUILD    : 0   # Special variable for forcing build on only one target
  OSX         : 0

#before_script:
  # Load NEMO
  #- source /opt/usr/nemo/nemo_start.sh
  #- echo ${NEMO}
  # clone
  #- git clone https://gitlab.lam.fr/jclamber/unsio.git
  #- cd unsio
  #- git branch -r
  #- git checkout origin/new_cmake

#
# OSX
#
OSX:
  stage : build
  tags:
    - osx
  only :
    variables:
      - $OSX == "1"
      - $ONEBUILD == "1"
  script:
    # build
    - CI/scripts/buildOSX.sh
  artifacts:
    name: "macos"
    paths:
      - glnemo2*.dmg
    expire_in: 1 week

#
# RPM Distros
#
fedora35 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/fedora35
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "fedora35"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

fedora34 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/fedora34
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "fedora34"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

fedora33 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/fedora33
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "fedora33"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

# OpenSUSE
opensuse15.3 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/opensuse15.3
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "opensuse15.3"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

opensuse15.2 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/opensuse15.2
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "opensuse15.2"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

opensuse-rolling :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/tumbleweed
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "tumebleweed"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

centos7 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/centos7
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "centos7"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

centos8 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/centos8
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "centos8"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

# Ubuntu
ubuntu16.04 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/ubuntu16.04
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu16.04"
    paths:
      - glnemo2*.deb
    expire_in: 1 week

ubuntu21.10 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/ubuntu21.10
  only :
       variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu21.10"
    paths:
      - glnemo2*.deb
    expire_in: 1 week

ubuntu20.04 :
  stage : build
  image: registry.lam.fr/jclamber/glnemo2/ubuntu20.04
  only :
       variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu20.04"
    paths:
      - glnemo2*.deb
    expire_in: 1 week
