#
# Copyright Jean-Charles Lambert, 2020
#
# - YAML file for Continous Integration / Continous Deployement
# - glnemo2 packages (RPM or DEB) are automatically
#   generated at new commit for different linux distribution
#
# - Documentation :
#   https://docs.gitlab.com/ee/ci/yaml/

stages:
- build

variables :
  BUILD       : 0
  ONEBUILD    : 0   # Special variable for forcing build on only one target
  OSX         : 0

#before_script:
  # Load NEMO
  #- source /opt/usr/nemo/nemo_start.sh
  #- echo ${NEMO}
  # clone
  #- git clone https://gitlab.lam.fr/jclamber/unsio.git
  #- cd unsio
  #- git branch -r
  #- git checkout origin/new_cmake

#
# RPM Distros
#
fedora31 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/fedora31
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "fedora31"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

fedora30 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/fedora30
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "fedora30"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

# OpenSUSE
opensuse15.1 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/opensuse15.1
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "opensuse15.1"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

opensuse-rolling :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/tumbleweed
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "tumebleweed"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

centos7 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/centos7
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "centos7"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

centos8 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/centos8
  only :
      variables:
        - $ONEBUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "centos8"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

# Ubuntu
ubuntu16.04 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/ubuntu16.04
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu16.04"
    paths:
      - glnemo2*.deb
    expire_in: 1 week

ubuntu18.04 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/ubuntu18.04
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu18.04"
    paths:
      - glnemo2*.deb
    expire_in: 1 week

ubuntu19.10 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/ubuntu19.10
  only :
       variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "ubuntu19.10"
    paths:
      - glnemo2*.deb
    expire_in: 1 week

# mageia
#
mageia6 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/mageia6
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "mageia6"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week

mageia7 :
  stage : build
  image: portus.lam.fr/jclamber/glnemo2/mageia7
  only :
      variables:
        - $BUILD == "1"
  script:
    # build
    - CI/scripts/build.sh
  artifacts:
    name: "mageia7"
    paths:
      - glnemo2*.rpm
    expire_in: 1 week