FROM ubuntu:14.04

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install --fix-missing \
    cmake \
    dpkg-dev \
    file \
    g++ \
    gcc \
    libccfits-dev \
    make \
    subversion \
    git \
    libglm-dev \
    qt5-default \
    libhdf5-dev

cmd ["/bin/bash"]

