FROM fedora:28

RUN /usr/bin/dnf -y update
RUN /usr/bin/dnf -y install qt5-qtbase-devel.x86_64 make cmake gcc-c++ git glm-devel subversion CCfits-devel mesa-libGLU-devel.x86_64 zlib-devel rpm-build hdf5-devel libsq3-devel.x86_64 python3-devel.x86_64 python2-devel.x86_64 python-numpy python3-numpy python-setuptools python3-setuptools swig

cmd ["/bin/bash"]

