FROM ubuntu:15.04

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install \
    cmake \
    dpkg-dev \ 
    file \
    g++ \
    gcc \
    libccfits-dev \
    make \
    subversion \
    qt5-default \
    libhdf5-dev

cmd ["/bin/bash"]

