FROM ubuntu:16.04

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install --fix-missing \
    cmake \
    dpkg-dev \
    file \
    g++ \
    gcc \
    libccfits-dev \
    make \
    subversion \
    git \
    libglm-dev \
    qt5-default \
    libhdf5-dev \
    vim libsqlite3-dev python3-stdeb fakeroot python3-all-dev python3-all swig python3-numpy python3-setuptools \
    python-stdeb fakeroot python-all-dev python-all swig python-numpy python-setuptools


cmd ["/bin/bash"]

